@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RelateCommandParser" as RelateParser LOGIC_COLOR_T4
participant ":RelateCommand" as RelateCommand LOGIC_COLOR_T4
participant "predicate :RelateToPersonPredicate" as Predicate LOGIC_COLOR_T4

end box

box Model MODEL_COLOR_T1
participant "model :Model" as Model MODEL_COLOR
end box



[-> LogicManager : execute(relate)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(relate)
activate AddressBookParser

create RelateParser
AddressBookParser -> RelateParser
activate RelateParser



create RelateCommand
RelateParser -> RelateCommand : parse()
activate RelateCommand

RelateCommand --> RelateParser
deactivate RelateCommand

RelateParser --> AddressBookParser
deactivate RelateParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> RelateCommand : execute()
activate RelateCommand

RelateCommand -> Model: getFilteredPersonList()

create Predicate
RelateParser -> Predicate :
activate Predicate

Predicate --> RelateCommand
deactivate Predicate

RelateCommand -> Model: updateFilteredPersonList(predicate)

Model --> RelateCommand

RelateCommand --> LogicManager : result










@enduml